/** @format */

//defining types of actions
export const ActionTypes = {
	SET_AUTH_STATE: 'SET_AUTH_STATE',
	ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
	FETCH_PRODUCTS: 'FETCH_PRODUCTS',
	FETCH_CATEGORY_IMAGES: 'FETCH_CATEGORY_IMAGES',
};
